# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d12f0b0c9a6da4ce1168282127a3df580347561340d2cd76dad634b3d151c653a4898eae17b22b8e7c7aa0607f748ef3ed29e8a7d9b15c85111ca416c56bf0c

test:
  secret_key_base: b341a45be469bf536c8c4a151314a406b2db90467c29c1539b307a1c32486246b5a0b2b8a5d6de7957ac190a26dee7286cfb9b91121e0cbe823f58c026716788

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
